PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE regions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE 
);

CREATE TABLE cities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    regions_id INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE, 
    FOREIGN KEY (regions_id) REFERENCES regions(id)
);

